const moviesTypes = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAIL: 'FETCH_TOP_NEWS_FAIL',

  FETCH_POPULAR_MOVIES: 'FETCH_POPULAR_MOVIES',
  FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
  FETCH_POPULAR_MOVIES_FAIL: 'FETCH_POPULAR_MOVIES_FAIL',
};
export default moviesTypes;
